// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm668t6Bug0NTE0yOrHGzyFqhOnRN0H2U',
    appId: '1:648634245308:web:32784c2bcebcf9dda070b9',
    messagingSenderId: '648634245308',
    projectId: 'instagram-clone-bee54',
    authDomain: 'instagram-clone-bee54.firebaseapp.com',
    storageBucket: 'instagram-clone-bee54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3qllwWkEm3WfYEwFzuAbJ4XHgqkTboU',
    appId: '1:648634245308:android:a9446ae297e79d0aa070b9',
    messagingSenderId: '648634245308',
    projectId: 'instagram-clone-bee54',
    storageBucket: 'instagram-clone-bee54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGHvqbIIkmEFXc_4CV8FVYBSIaS4eNHmI',
    appId: '1:648634245308:ios:f0da72850e9aa0a2a070b9',
    messagingSenderId: '648634245308',
    projectId: 'instagram-clone-bee54',
    storageBucket: 'instagram-clone-bee54.appspot.com',
    iosClientId: '648634245308-le66v2u11j5rk8jpg1co6onm3qgu94pr.apps.googleusercontent.com',
    iosBundleId: 'com.ruvima.instagramCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGHvqbIIkmEFXc_4CV8FVYBSIaS4eNHmI',
    appId: '1:648634245308:ios:f0da72850e9aa0a2a070b9',
    messagingSenderId: '648634245308',
    projectId: 'instagram-clone-bee54',
    storageBucket: 'instagram-clone-bee54.appspot.com',
    iosClientId: '648634245308-le66v2u11j5rk8jpg1co6onm3qgu94pr.apps.googleusercontent.com',
    iosBundleId: 'com.ruvima.instagramCloneFlutter',
  );
}
